version: '3'
services:
  mongo-cinema:
    image: mongo:latest
    ports:
      - 27018:27017
    volumes:
      - db-data:/data/db
      - mongo-config:/data/configdb

volumes:
  db-data:
  mongo-config:
